### ISSUE TITLE
Chunking creates Composite topic instead of nested topicrefs

### ISSUE THREAD

**Issue by nakohdo** [dita-ot/org.dita.normalize#8]
When using chunking, a _Composite_ topic is created instead of nested topicrefs like in the original map.

## Original map
```xml
<topicref href="concepts/springFlowers.dita" chunk="to-content">
    <topicref href="topics/flowers/iris.dita"/>
    <topicref href="topics/flowers/snowdrop.dita"/>
</topicref>
```

generates the following

## Normalized map
```xml
<topicref href="concepts/springFlowers.dita#springFlowers" type="concept" chunk="to-content">
    <topicref href="concepts/springFlowers.dita#iris" type="topic"/>
    <topicref href="concepts/springFlowers.dita#snowdrop" type="topic"/>
</topicref>
```

## Composite topic _springFlowers.dita_
```xml
<!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "dita.dtd">
<dita>
  <concept id="springFlowers">
    <title>Spring Flowers</title>
    <topic id="iris">
      <title>Iris</title>
      <topic id="use">
        <title>Use</title>
      </topic>
    </topic>
    <topic id="snowdrop">
      <title>Snowdrop</title>
    </topic>
  </concept>
</dita>
```

According to the following references, _Composite_ topics are regarded obsolete and might be deprecated in the future. So if there is no compelling technical reason for using _Composite_ topics I'd prefer getting nested topicrefs in the output, which would simplify further processing.
- [Composite (ditabase)](https://www.oxygenxml.com/dita/styleguide/webhelp-feedback/index.html#Artefact/Topics_and_Information_Types/c_Using_Ditabase.html), DITA Style Guide by Tony Self
- [Chunking and Composite Topics](https://lists.oasis-open.org/archives/dita/201312/msg00007.html) by Chris Nitchie

Best regards,  
Frank

**Comment by robander** [comment]
Couple of things...

This appears to be an issue against the general DITA-OT, so it should really be opened against DITA-OT (https://github.com/dita-ot/dita-ot/issues) rather than against the normalization plugin.

That said though - I don't think there is much chance of this changing, for a few reasons:

- The chunking code is really hard to deal with -- it's old, tangled, and complicated, with more bug reports against it than almost any other section of the code. So a major design change is a bad idea unless there is a strong benefit (such as a change that would obsolete some of those other issues) -- this suggested change is unlikely to fix any of those other issues.
- The `<dita>` container is required for cases where `chunk="to-content"` is specified on a map, or on a `<topicgroup>` style element -- otherwise you end up with peer topics at the root level, which is invalid. Using the same design for that condition as for single branches like your sample simplifies the code.
- While some people oppose using composite topics in general, they are certainly not obsolete, and so far there is no indication that they will be deprecated. (I raised the idea with a couple of OASIS members some months ago and got a "don't even think about it" response.) At present nobody has proposed removing that document type from DITA 2.0, and if it's in 2.0 then it's going to be part of standard DITA for many years to come.

**Comment by robander** [comment]
To clarify my comment about this being a DITA-OT issue -- the input/output of the chunking process is standard across all DITA-OT transform types - it's just that it's not usually visible because you don't see the normalized DITA that goes into generating PDF, HTML5, etc. 

Thinking about it more broadly now -- it won't surprise me if other similar issues are opened here in the future -- issues that reflect how DITA is normalized for all transformation types, but have been invisible to most people until this "return normalized DITA to me" transform type came along.

Regardless - I'm going to mark this closed because the issue / request is part of the common DITA-OT chunking module, and is not specific to the normalization plugin. 

If you do want to help redesign how this chunking process works, I'd suggest discussing them in the [DITA-OT Slack channel](https://slack.dita-ot.org) before opening a copy of this issue in the main tracker, just because all of the issues I highlighted in my previous comment make the requested change unlikely at this point.

**Comment by nakohdo** [comment]
Thanks for the detailed explanation of the rationale behind using _composite_ topics and the update on the current discussion at OASIS about this topic.

The reason for bringing this up here was that our DITA specialization currently doesn't support _composite_ topics so the normalized DITA wasn't valid. I suppose we will add _composite_ support now due to the request of creating normalized DITA from our specialized DITA files.

Best regards,
Frank
